language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: f0fa9482a2021047aaf18b59838766fbfe021b0b
 local_dir: dist
 on:
   branch: master
